FROM jupyter/scipy-notebook:8e15d329f1e9

# 
RUN conda install jupyter
RUN conda install -c conda-forge nbgrader
RUN conda install -c damianavila82 rise
RUN conda install -c conda-forge ipyvolume
RUN pip install plotly

# Will be enabled by default afaik, but ipyvolume recommends its verified.
RUN jupyter nbextension enable --py --sys-prefix widgetsnbextension

# nbgrader - student-mode rather than instructor-mode
RUN jupyter nbextension disable --sys-prefix create_assignment/main
RUN jupyter nbextension disable --sys-prefix formgrader/main --section=tree
RUN jupyter serverextension disable --sys-prefix nbgrader.server_extensions.formgrader